export const END_POINT = {
  SIGN_UP: "signup",
  VERIFY_EMAIL: "confirm-email",
  CONFIRM_REGISTER: "confirm-register",
  LOGIN: "login",
  PROFILE: "me",
  BLOG: "blogs",
  UPDADTEPROFILE: "updateprofile",
  LOGOUT: "logout",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  CHANGE_PASSWORD: "change-password",
  PRODUCTS: "public/products",
  COMMENTS: "products/comments",
  CATEGORIES: "public/categories",
  WISHLIST: "wishlist",
  ORDERS: "orders",
  ORDERSVNPAY: "vnpay_payment",
  FEEDBACK: "products/comments",
};
